baseURL: https://siddharth-gulati.netlify.app/
languageCode: en-us
title: Siddharth Gulati
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get To Know Me!
    subtitle: |-
      Currently pursuing Masters in Analytics and Management (MAM) at London Business School (LBS).
    title: Hi, I'm Sid!
  blog: {}
  contact:
    address:
      - city: London, NW1 5AQ
        country: United Kingdom
        street: 142, Dorset House, Glouscter Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
    - email: sgulati.mam2023@london.edu
    enable: yes
    phone:
      - phone: +44 7778905776
        title: Phone
  custom_css: []
  custom_js: []
  description: Masters in Analytics and Management (MAM) at London Business School (LBS)
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/siddharth_gulati
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/SiddharthGulati98
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/siddharth-gulati98/
  image: ''
  name: Siddharth
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Download CV
        url: blogs/CV.pdf
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
    menu: Menu
    subtitle: 
    title: Siddharth Gulati
  tiles:
    enable: yes
    showcase:
      - image: photo1.jpeg
        subtitle: Click to view my Resume
        title: Resume
        url: blogs/aliquam
      - image: imdb.jpeg
        subtitle: Click to view the data and results
        title: IMDB Ratings Project
        url: blogs/idmb_ratings
      - image: bay.jpeg
        subtitle: Click to view the data and results
        title: Rents in San Francisco
        url: blogs/magna
      - image: stock.jpeg
        subtitle: Click to view the data and results
        title: Stock Financial Analysis
        url: blogs/stock_analysis
      - image: superbowl.jpeg
        subtitle: Click to view the data and results
        title: Average Weekly Sales During Holidays
        url: blogs/new_blog
      - image: climate.jpeg
        subtitle: Click to view the data and results
        title: Climate Change & Temperature Analysis
        url: blogs/climate
  two:
    enable: yes
    subtitle: "Currently a student at LBS, I have worked as a Senior Data Analyst (Product + Growth) at Airtel X Labs. I am a highly motivated individual, capable of delivering effective and timely results. I have internship experience at organisations including Airtel, American Express and HCL Technologies Ltd. 

Apart from this, I was recently selected as an International Delegate for the Harvard College Project for Asian and International Relations (HPAIR) Conference 2020, held at Harvard University. 

Being an ambitious and result-driven person, I have clearly defined goals and never hesitate to escape my comfort zone to face new challenges. I possess good analytical, logical, inter-personal and communication skills, and have a keen interest in Analytics, Strategy and Product."
    title: About Siddharth
    
    
    
    
    
    
    
    
